// Copyright IBM Corp. 2026

// Code generated by go run ./tools/providers/run generate-source -root .; DO NOT EDIT.
package main

import (
	"context"
	"errors"
	"reflect"
	"testing"

	generatedruntimeassets "github.com/hashicorp/terraform-provider-ubuntu/generated/providers/ubuntu/runtimeassets"
	"github.com/hashicorp/terraform-provider-ubuntu/providers/shared/assets"
	"github.com/hashicorp/terraform-provider-ubuntu/providers/shared/catalog"
	coreprovider "github.com/hashicorp/terraform-provider-ubuntu/providers/shared/serving"
)

func TestMainServesProviderWithExpectedConfig(t *testing.T) {
	assetStore := assets.NewMemoryStore(generatedruntimeassets.RuntimeAssetSpec, nil, nil)
	serveCalled := false
	fatalCalled := false

	withProviderMainStubs(t,
		func() (assets.Store, error) {
			return assetStore, nil
		},
		func(_ context.Context, config coreprovider.ProviderConfig, address string, providerCatalog catalog.Catalog) error {
			serveCalled = true
			if config.Name != providerSpec.Name {
				t.Fatalf("config.Name = %q, want %q", config.Name, providerSpec.Name)
			}
			if config.Prefix != providerSpec.Name {
				t.Fatalf("config.Prefix = %q, want %q", config.Prefix, providerSpec.Name)
			}
			if config.Assets != assetStore {
				t.Fatalf("config.Assets = %v, want %v", config.Assets, assetStore)
			}
			if config.Version != coreprovider.FormatProviderVersion(version, commit) {
				t.Fatalf("config.Version = %q, want %q", config.Version, coreprovider.FormatProviderVersion(version, commit))
			}
			if address != providerSpec.Address {
				t.Fatalf("address = %q, want %q", address, providerSpec.Address)
			}
			if !reflect.DeepEqual(providerCatalog.AssetSpec(), generatedruntimeassets.RuntimeAssetSpec) {
				t.Fatalf("catalog asset spec = %#v, want %#v", providerCatalog.AssetSpec(), generatedruntimeassets.RuntimeAssetSpec)
			}
			return nil
		},
		func(err error) {
			fatalCalled = true
			t.Fatalf("fatalProviderFunc called unexpectedly: %v", err)
		},
	)

	main()

	if !serveCalled {
		t.Fatal("serveProviderFunc was not called")
	}
	if fatalCalled {
		t.Fatal("fatalProviderFunc should not be called on success")
	}
}

func TestMainFatalsOnLoadRuntimeAssetsError(t *testing.T) {
	expectedErr := errors.New("load failed")
	var fatalErr error
	serveCalled := false

	withProviderMainStubs(t,
		func() (assets.Store, error) {
			return nil, expectedErr
		},
		func(context.Context, coreprovider.ProviderConfig, string, catalog.Catalog) error {
			serveCalled = true
			return nil
		},
		func(err error) {
			fatalErr = err
		},
	)

	main()

	if serveCalled {
		t.Fatal("serveProviderFunc should not be called when asset loading fails")
	}
	if !errors.Is(fatalErr, expectedErr) {
		t.Fatalf("fatal error = %v, want %v", fatalErr, expectedErr)
	}
}

func TestMainFatalsOnServeProviderError(t *testing.T) {
	expectedErr := errors.New("serve failed")
	assetStore := assets.NewMemoryStore(generatedruntimeassets.RuntimeAssetSpec, nil, nil)
	var fatalErr error

	withProviderMainStubs(t,
		func() (assets.Store, error) {
			return assetStore, nil
		},
		func(context.Context, coreprovider.ProviderConfig, string, catalog.Catalog) error {
			return expectedErr
		},
		func(err error) {
			fatalErr = err
		},
	)

	main()

	if !errors.Is(fatalErr, expectedErr) {
		t.Fatalf("fatal error = %v, want %v", fatalErr, expectedErr)
	}
}

func withProviderMainStubs(
	t *testing.T,
	load func() (assets.Store, error),
	serve func(context.Context, coreprovider.ProviderConfig, string, catalog.Catalog) error,
	fatal func(error),
) {
	t.Helper()
	oldLoad := loadRuntimeAssetsFunc
	oldServe := serveProviderFunc
	oldFatal := fatalProviderFunc
	t.Cleanup(func() {
		loadRuntimeAssetsFunc = oldLoad
		serveProviderFunc = oldServe
		fatalProviderFunc = oldFatal
	})
	if load != nil {
		loadRuntimeAssetsFunc = load
	}
	if serve != nil {
		serveProviderFunc = serve
	}
	if fatal != nil {
		fatalProviderFunc = fatal
	}
}
