// Code generated by go run ./tools/providers/run generate-source -root .; DO NOT EDIT.
package main

import (
	"context"
	"log"

	generatedruntimeassets "github.com/hashicorp/terraform-provider-ubuntu/generated/providers/ubuntu/runtimeassets"
	"github.com/hashicorp/terraform-provider-ubuntu/providers/shared/catalog"
	coreprovider "github.com/hashicorp/terraform-provider-ubuntu/providers/shared/serving"
)

var providerSpec = catalog.MustProviderSpec("ubuntu")

var version = "dev"
var commit = "unknown"

var (
	loadRuntimeAssetsFunc = generatedruntimeassets.LoadFromEnv
	serveProviderFunc     = catalog.ServeProvider
	fatalProviderFunc     = func(err error) { log.Fatal(err) }
)

func main() {
	assets, err := loadRuntimeAssetsFunc()
	if err != nil {
		fatalProviderFunc(err)
		return
	}

	config := coreprovider.ProviderConfig{
		Name:          providerSpec.Name,
		Prefix:        providerSpec.Name,
		Assets:        assets,
		SupportPolicy: providerSpec.SupportPolicy,
		Version:       coreprovider.FormatProviderVersion(version, commit),
	}

	if err := serveProviderFunc(context.Background(), config, providerSpec.Address, providerSpec.Catalog); err != nil {
		fatalProviderFunc(err)
	}
}
