package main

import (
	"reflect"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-provider-ubuntu/guest/sdk"
	linuxfilescontract "github.com/hashicorp/terraform-provider-ubuntu/guest/sdk/contracts/linuxfiles"
)

func TestCrontabEntrySchemaMatchesContract(t *testing.T) {
	schema := (&crontabEntryResource{}).Schema()
	if !reflect.DeepEqual(schema, linuxfilescontract.CrontabEntryResourceSchema()) {
		t.Fatal("crontab entry schema did not match shared contract")
	}
}

func TestCrontabEntryValidateScheduleExclusivity(t *testing.T) {
	err := (&crontabEntryResource{}).Validate(pluginsdk.StateData{
		"name":     "backup",
		"user":     "tf",
		"command":  "/opt/backup.sh",
		"schedule": "0 2 * * *",
		"minute":   "0",
	})
	if err == nil || !strings.Contains(err.Error(), "mutually exclusive") {
		t.Fatalf("expected mutually-exclusive schedule validation error, got %v", err)
	}
}

func TestCrontabEntryValidateInvalidName(t *testing.T) {
	err := (&crontabEntryResource{}).Validate(pluginsdk.StateData{
		"name":     "backup job",
		"user":     "tf",
		"command":  "/opt/backup.sh",
		"schedule": "0 2 * * *",
	})
	if err == nil || !strings.Contains(err.Error(), "match [A-Za-z0-9._-]+") {
		t.Fatalf("expected invalid-name validation error, got %v", err)
	}
}

func TestCrontabEntryCreateNewManagedEntry(t *testing.T) {
	fake := newFakeCrontabHost()
	withFakeCrontabHost(t, fake)

	state, err := (&crontabEntryResource{}).Create(pluginsdk.StateData{
		"name":     "backup",
		"user":     "tf",
		"command":  "/opt/backup.sh",
		"schedule": "0 2 * * *",
	})
	if err != nil {
		t.Fatalf("Create returned error: %v", err)
	}
	if got, want := fake.users["tf"], "# tf-nix: crontab_entry name=backup\n0 2 * * * /opt/backup.sh\n"; got != want {
		t.Fatalf("unexpected crontab content:\nwant: %q\ngot:  %q", want, got)
	}
	if state.GetString("id") != "tf/backup" || state.GetString("schedule") != "0 2 * * *" {
		t.Fatalf("unexpected state: %#v", state)
	}
}

func TestCrontabEntryCreateAdoptsExistingMatch(t *testing.T) {
	fake := newFakeCrontabHost()
	fake.users["tf"] = "0 2 * * * /opt/backup.sh\n"
	withFakeCrontabHost(t, fake)

	_, err := (&crontabEntryResource{}).Create(pluginsdk.StateData{
		"name":     "backup",
		"user":     "tf",
		"command":  "/opt/backup.sh",
		"schedule": "0 2 * * *",
	})
	if err != nil {
		t.Fatalf("Create returned error: %v", err)
	}
	if got, want := fake.users["tf"], "# tf-nix: crontab_entry name=backup\n0 2 * * * /opt/backup.sh\n"; got != want {
		t.Fatalf("unexpected adopted crontab content:\nwant: %q\ngot:  %q", want, got)
	}
}

func TestCrontabEntryCreateRejectsExistingManagedEntry(t *testing.T) {
	fake := newFakeCrontabHost()
	fake.users["tf"] = "# tf-nix: crontab_entry name=backup\n0 2 * * * /opt/backup.sh\n"
	withFakeCrontabHost(t, fake)

	_, err := (&crontabEntryResource{}).Create(pluginsdk.StateData{
		"name":     "backup",
		"user":     "tf",
		"command":  "/opt/backup.sh",
		"schedule": "0 2 * * *",
	})
	if err == nil || !strings.Contains(err.Error(), "import it before managing with terraform") {
		t.Fatalf("expected import-required error, got %v", err)
	}
}

func TestCrontabEntryCreateRejectsAmbiguousAdoption(t *testing.T) {
	fake := newFakeCrontabHost()
	fake.users["tf"] = "0 2 * * * /opt/backup.sh\n0 2 * * * /opt/backup.sh\n"
	withFakeCrontabHost(t, fake)

	_, err := (&crontabEntryResource{}).Create(pluginsdk.StateData{
		"name":     "backup",
		"user":     "tf",
		"command":  "/opt/backup.sh",
		"schedule": "0 2 * * *",
	})
	if err == nil || !strings.Contains(err.Error(), "multiple unmanaged crontab entries") {
		t.Fatalf("expected ambiguous-adoption error, got %v", err)
	}
}

func TestCrontabEntryReadAndImportState(t *testing.T) {
	fake := newFakeCrontabHost()
	fake.users["tf"] = "# DO NOT EDIT THIS FILE\n# tf-nix: crontab_entry name=backup\n@daily /opt/backup.sh\n"
	withFakeCrontabHost(t, fake)

	resource := &crontabEntryResource{}
	state, err := resource.Read(pluginsdk.StateData{"user": "tf", "name": "backup"})
	if err != nil {
		t.Fatalf("Read returned error: %v", err)
	}
	if state.GetString("schedule") != "@daily" || state.GetString("command") != "/opt/backup.sh" {
		t.Fatalf("unexpected read state: %#v", state)
	}

	imported, err := resource.ImportState("tf/backup")
	if err != nil {
		t.Fatalf("ImportState returned error: %v", err)
	}
	if imported.GetString("id") != "tf/backup" {
		t.Fatalf("unexpected imported state: %#v", imported)
	}
}

func TestCrontabEntryUpdateByMarker(t *testing.T) {
	fake := newFakeCrontabHost()
	fake.users["tf"] = "MAILTO=ops@example.com\n# tf-nix: crontab_entry name=backup\n0 2 * * * /opt/backup.sh\n"
	withFakeCrontabHost(t, fake)

	state, err := (&crontabEntryResource{}).Update(
		pluginsdk.StateData{
			"name":     "backup",
			"user":     "tf",
			"command":  "/opt/backup.sh",
			"schedule": "0 2 * * *",
		},
		pluginsdk.StateData{
			"name":     "backup",
			"user":     "tf",
			"command":  "/opt/nightly.sh",
			"schedule": "@daily",
		},
	)
	if err != nil {
		t.Fatalf("Update returned error: %v", err)
	}
	want := "MAILTO=ops@example.com\n# tf-nix: crontab_entry name=backup\n@daily /opt/nightly.sh\n"
	if got := fake.users["tf"]; got != want {
		t.Fatalf("unexpected updated crontab content:\nwant: %q\ngot:  %q", want, got)
	}
	if state.GetString("schedule") != "@daily" || state.GetString("command") != "/opt/nightly.sh" {
		t.Fatalf("unexpected updated state: %#v", state)
	}
}

func TestCrontabEntryUpdateCreatesManagedEntryWhenMissingOnHost(t *testing.T) {
	fake := newFakeCrontabHost()
	fake.users["root"] = ""
	withFakeCrontabHost(t, fake)

	state, err := (&crontabEntryResource{}).Update(
		pluginsdk.StateData{
			"name":     "tf_nix_heartbeat",
			"user":     "root",
			"command":  "/usr/local/bin/tf-linux-heartbeat.sh",
			"schedule": "*/5 * * * *",
		},
		pluginsdk.StateData{
			"name":     "tf_nix_heartbeat",
			"user":     "root",
			"command":  "/usr/local/bin/tf-linux-heartbeat.sh",
			"schedule": "*/5 * * * *",
		},
	)
	if err != nil {
		t.Fatalf("Update returned error: %v", err)
	}
	want := "# tf-nix: crontab_entry name=tf_nix_heartbeat\n*/5 * * * * /usr/local/bin/tf-linux-heartbeat.sh\n"
	if got := fake.users["root"]; got != want {
		t.Fatalf("unexpected crontab content after create-on-update:\nwant: %q\ngot:  %q", want, got)
	}
	if state.GetString("id") != "root/tf_nix_heartbeat" {
		t.Fatalf("unexpected updated state: %#v", state)
	}
}

func TestCrontabEntryUpdateMovesManagedEntryAcrossUsers(t *testing.T) {
	fake := newFakeCrontabHost()
	fake.users["tf"] = "# tf-nix: crontab_entry name=backup\n0 2 * * * /opt/backup.sh\n"
	fake.users["root"] = "MAILTO=root@example.com\n"
	withFakeCrontabHost(t, fake)

	state, err := (&crontabEntryResource{}).Update(
		pluginsdk.StateData{
			"name":     "backup",
			"user":     "tf",
			"command":  "/opt/backup.sh",
			"schedule": "0 2 * * *",
		},
		pluginsdk.StateData{
			"name":     "backup_root",
			"user":     "root",
			"command":  "/opt/root-backup.sh",
			"schedule": "@daily",
		},
	)
	if err != nil {
		t.Fatalf("Update returned error: %v", err)
	}
	if _, ok := fake.users["tf"]; ok {
		t.Fatalf("expected prior user crontab to be removed, got %q", fake.users["tf"])
	}
	wantRoot := "MAILTO=root@example.com\n# tf-nix: crontab_entry name=backup_root\n@daily /opt/root-backup.sh\n"
	if got := fake.users["root"]; got != wantRoot {
		t.Fatalf("unexpected root crontab content:\nwant: %q\ngot:  %q", wantRoot, got)
	}
	if state.GetString("id") != "root/backup_root" || state.GetString("schedule") != "@daily" {
		t.Fatalf("unexpected updated state: %#v", state)
	}
}

func TestCrontabEntryDeleteRemovesManagedBlockOnly(t *testing.T) {
	fake := newFakeCrontabHost()
	fake.users["tf"] = "MAILTO=ops@example.com\n# tf-nix: crontab_entry name=backup\n0 2 * * * /opt/backup.sh\n@daily /opt/other.sh\n"
	withFakeCrontabHost(t, fake)

	err := (&crontabEntryResource{}).Delete(pluginsdk.StateData{
		"name": "backup",
		"user": "tf",
	})
	if err != nil {
		t.Fatalf("Delete returned error: %v", err)
	}
	want := "MAILTO=ops@example.com\n@daily /opt/other.sh\n"
	if got := fake.users["tf"]; got != want {
		t.Fatalf("unexpected remaining crontab content:\nwant: %q\ngot:  %q", want, got)
	}
}

func TestCrontabEntryCreateFailsWithoutCrontabCommand(t *testing.T) {
	fake := newFakeCrontabHost()
	fake.hasCrontab = false
	withFakeCrontabHost(t, fake)

	_, err := (&crontabEntryResource{}).Create(pluginsdk.StateData{
		"name":     "backup",
		"user":     "tf",
		"command":  "/opt/backup.sh",
		"schedule": "0 2 * * *",
	})
	if err == nil || !strings.Contains(err.Error(), "install a cron implementation") {
		t.Fatalf("expected missing-crontab error, got %v", err)
	}
}

func TestRemoveUserCrontabTreatsMissingAsSuccess(t *testing.T) {
	fake := newFakeCrontabHost()
	withFakeCrontabHost(t, fake)

	if err := removeUserCrontab("missing"); err != nil {
		t.Fatalf("removeUserCrontab() error = %v, want nil", err)
	}
}

func TestRemoveUserCrontabRemovesExistingUserCrontab(t *testing.T) {
	fake := newFakeCrontabHost()
	fake.users["tf"] = "0 2 * * * /opt/backup.sh\n"
	withFakeCrontabHost(t, fake)

	if err := removeUserCrontab("tf"); err != nil {
		t.Fatalf("removeUserCrontab() error = %v, want nil", err)
	}
	if _, ok := fake.users["tf"]; ok {
		t.Fatal("expected crontab to be removed for tf")
	}
}

func TestCrontabResultMessagePrefersStderrThenStdout(t *testing.T) {
	if got := crontabResultMessage(nil); got != "" {
		t.Fatalf("crontabResultMessage(nil) = %q, want empty string", got)
	}
	if got := crontabResultMessage(&pluginsdk.CmdResult{Stdout: "stdout message\n"}); got != "stdout message" {
		t.Fatalf("crontabResultMessage(stdout) = %q, want stdout message", got)
	}
	if got := crontabResultMessage(&pluginsdk.CmdResult{Stdout: "stdout message\n", Stderr: "stderr message\n"}); got != "stderr message" {
		t.Fatalf("crontabResultMessage(stderr) = %q, want stderr message", got)
	}
}

type fakeCrontabHost struct {
	hasCrontab bool
	users      map[string]string
	tempFiles  map[string][]byte
}

func newFakeCrontabHost() *fakeCrontabHost {
	return &fakeCrontabHost{
		hasCrontab: true,
		users:      make(map[string]string),
		tempFiles:  make(map[string][]byte),
	}
}

func withFakeCrontabHost(t *testing.T, fake *fakeCrontabHost) {
	t.Helper()

	origHasCommand := pluginsdk.HasCommand
	origCmdExec := pluginsdk.CmdExec
	origFileWrite := pluginsdk.FileWrite

	t.Cleanup(func() {
		pluginsdk.HasCommand = origHasCommand
		pluginsdk.CmdExec = origCmdExec
		pluginsdk.FileWrite = origFileWrite
	})

	pluginsdk.HasCommand = func(name string) (bool, error) {
		if name == "crontab" {
			return fake.hasCrontab, nil
		}
		return true, nil
	}
	pluginsdk.FileWrite = func(path string, data []byte, mode uint32) error {
		fake.tempFiles[path] = append([]byte(nil), data...)
		_ = mode
		return nil
	}
	pluginsdk.CmdExec = func(cmd string, args []string) (*pluginsdk.CmdResult, error) {
		switch cmd {
		case "crontab":
			if len(args) < 2 || args[0] != "-u" {
				return &pluginsdk.CmdResult{ExitCode: 1, Stderr: "unexpected crontab args"}, nil
			}
			user := args[1]
			if len(args) == 3 && args[2] == "-l" {
				content, ok := fake.users[user]
				if !ok {
					return &pluginsdk.CmdResult{ExitCode: 1, Stderr: "no crontab for " + user}, nil
				}
				return &pluginsdk.CmdResult{ExitCode: 0, Stdout: content}, nil
			}
			if len(args) == 3 && args[2] == "-r" {
				if _, ok := fake.users[user]; !ok {
					return &pluginsdk.CmdResult{ExitCode: 1, Stderr: "no crontab for " + user}, nil
				}
				delete(fake.users, user)
				return &pluginsdk.CmdResult{ExitCode: 0}, nil
			}
			if len(args) == 3 {
				content, ok := fake.tempFiles[args[2]]
				if !ok {
					return &pluginsdk.CmdResult{ExitCode: 1, Stderr: "missing temp file"}, nil
				}
				fake.users[user] = string(content)
				return &pluginsdk.CmdResult{ExitCode: 0}, nil
			}
			return &pluginsdk.CmdResult{ExitCode: 1, Stderr: "unexpected crontab args"}, nil
		case "rm":
			for _, path := range args[1:] {
				delete(fake.tempFiles, path)
			}
			return &pluginsdk.CmdResult{ExitCode: 0}, nil
		default:
			return &pluginsdk.CmdResult{ExitCode: 1, Stderr: "unexpected command: " + cmd}, nil
		}
	}
}

func parseTestCrontab(content string) []pluginsdk.CrontabLine {
	if content == "" {
		return nil
	}
	rawLines := strings.Split(content, "\n")
	if rawLines[len(rawLines)-1] == "" {
		rawLines = rawLines[:len(rawLines)-1]
	}
	lines := make([]pluginsdk.CrontabLine, 0, len(rawLines))
	for _, line := range rawLines {
		trimmed := strings.TrimSpace(line)
		switch {
		case trimmed == "":
			lines = append(lines, pluginsdk.CrontabLine{IsBlank: true, Raw: line})
		case strings.HasPrefix(trimmed, "#"):
			lines = append(lines, pluginsdk.CrontabLine{IsComment: true, Comment: trimmed, Raw: line})
		case strings.HasPrefix(trimmed, "@"):
			fields := strings.Fields(trimmed)
			lines = append(lines, pluginsdk.CrontabLine{Special: fields[0], Command: strings.TrimSpace(trimmed[len(fields[0]):])})
		default:
			fields := strings.Fields(trimmed)
			if len(fields) >= 6 {
				lines = append(lines, pluginsdk.CrontabLine{
					Minute:     fields[0],
					Hour:       fields[1],
					DayOfMonth: fields[2],
					Month:      fields[3],
					DayOfWeek:  fields[4],
					Command:    strings.Join(fields[5:], " "),
				})
				continue
			}
			if strings.Contains(trimmed, "=") && !strings.Contains(trimmed, " ") {
				lines = append(lines, pluginsdk.CrontabLine{IsEnv: true, Raw: line})
				continue
			}
			lines = append(lines, pluginsdk.CrontabLine{Raw: line})
		}
	}
	return lines
}

func serializeTestCrontab(lines []pluginsdk.CrontabLine) string {
	if len(lines) == 0 {
		return ""
	}
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		switch {
		case line.IsBlank:
			out = append(out, line.Raw)
		case line.IsComment:
			if line.Raw != "" {
				out = append(out, line.Raw)
			} else {
				out = append(out, line.Comment)
			}
		case line.IsEnv || line.Raw != "":
			out = append(out, line.Raw)
		case line.Special != "":
			out = append(out, strings.TrimSpace(line.Special)+" "+strings.TrimSpace(line.Command))
		default:
			out = append(out, strings.Join([]string{line.Minute, line.Hour, line.DayOfMonth, line.Month, line.DayOfWeek, strings.TrimSpace(line.Command)}, " "))
		}
	}
	return strings.Join(out, "\n") + "\n"
}
